name: CI Build and Push Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make mvnw executable
        run: |
          chmod +x ./hello-spring-k8s/mvnw

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: tranhuumanh123
          password: Huumanh123@
      

      - name: Build and push Hello Spring K8S image
        uses: docker/build-push-action@v5
        with:
          context: ./hello-spring-k8s
          push: true
          tags: duongwng/hello-spring-k8s:latest
          builder: ${{ steps.buildx.outputs.name }}
